### ISSUE TITLE
Prettier don't follow the same rules of ESlint : split the html attributes to multiple lines in .vue page

### ISSUE THREAD

**Issue by clabnet** [imomaliev/vue-ts#11]
Hi, very clean code this project. 

The App.vue  after `yarn format` command: 
```
<img alt="Vue logo" src="@/assets/logo.png" />
```

No changes in the page, after CTRL + S  (save command) on vscode :
```  
<img alt="Vue logo"
            src="@/assets/logo.png" />
```
**How to force Prettier to NOT split the html attributes to multiple lines ?**

![image](https://user-images.githubusercontent.com/6067610/174850065-f7a1849e-2fe6-4d9d-8cbd-009c7432e429.png)

Below my config files.

`tsconfig.json` : (no changes)
`prettierrc.js` : (no changes)
`package.json : `  (updated with `pnpm up`)
```
{
  "name": "vite-vue-typescript-starter",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "deploy": "vue-tsc --noEmit && vite build --base '/vue-ts/'",
    "preview": "vite preview",
    "format": "prettier --write .",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx,.vue",
    "test": "jest"
  },
  "dependencies": {
    "vue": "^3.2.37"
  },
  "devDependencies": {
    "@types/jest": "^28.1.2",
    "@typescript-eslint/eslint-plugin": "^5.29.0",
    "@typescript-eslint/parser": "^5.29.0",
    "@vitejs/plugin-vue": "^2.3.3",
    "@vue/test-utils": "^2.0.1",
    "@vue/vue3-jest": "^28.0.0",
    "eslint": "^8.18.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-jest": "^26.5.3",
    "eslint-plugin-vue": "^9.1.1",
    "jest": "^28.1.1",
    "jest-environment-jsdom": "^28.1.1",
    "jest-transform-stub": "^2.0.0",
    "prettier": "^2.7.1",
    "ts-jest": "^28.0.5",
    "typescript": "^4.7.4",
    "vite": "^2.9.12",
    "vue-eslint-parser": "^9.0.2",
    "vue-tsc": "^0.38.1"
  },
  "//devDependencies": {
    "vue-tsc": "do not update to 36+ because of DefineComponent issue"
  }
}
```

Thanks in advance.

**Comment by imomaliev** [comment]
@clabnet Hi. Thanks. Are there any changes to `.editorconfig` in your project? Or maybe you have multiple config files for `prettier`. Can you show me `ls -la` of the folder containing `package.json`?

**Comment by clabnet** [comment]
@Sardorbek, surely.

editorconfig was NOT changed.

Link to my Github repo :

https://github.com/clabnet/vue-ts-eslint-prettier

Root folder content:

📦vue-ts-eslint-prettier
  ┣ 📂public
  ┃ ┗ 📜favicon.ico
  ┣ 📂src
  ┃ ┣ 📂assets
  ┃ ┃ ┗ 📜logo.png
  ┃ ┣ 📂components
  ┃ ┃ ┗ 📜HelloWorld.vue
  ┃ ┣ 📜App.vue
  ┃ ┣ 📜env.d.ts
  ┃ ┗ 📜main.ts
  ┣ 📜.editorconfig
  ┣ 📜.eslintignore
  ┣ 📜.eslintrc.js
  ┣ 📜.gitignore
  ┣ 📜.npmrc
  ┣ 📜.pnpm-debug.log
  ┣ 📜.prettierignore
  ┣ 📜.prettierrc.js
  ┣ 📜desktop.ini
  ┣ 📜index.html
  ┣ 📜jest.config.js
  ┣ 📜LICENSE
  ┣ 📜package.json
  ┣ 📜pnpm-lock.yaml
  ┣ 📜README.md
  ┣ 📜tsconfig.json
  ┣ 📜tsconfig.node.json
  ┗ 📜vite.config.ts

Can be that vscode use other prettier config on saving ?

Thank you for your support.

**Comment by imomaliev** [comment]
@clabnet This looks like an issue with your VSCode. Sorry, but I do not use it, so I can't help you with that. Try disabling some plugins and see which one is the culprit.
